---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: teranode-operator
  name: teranode-operator-leader-election-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
{{- if .Values.deployment.env.watch_namespace }}
{{- $namespaces := .Values.deployment.env.watch_namespace | split "," }}
{{- range $namespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: teranode-operator-sr-role
  namespace: {{ $namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - deployments
      - configmaps
      - secrets
      - endpoints
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: teranode-operator
  name: teranode-operator-alertsystem-editor-role
rules:
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - alertsystems
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - alertsystems/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: teranode-operator
  name: teranode-operator-alertsystem-viewer-role
rules:
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - alertsystems
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - alertsystems/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teranode-operator-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - secrets
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - alertsystems
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - alertsystems/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - alertsystems/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - assets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - assets/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - assets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockassemblies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockassemblies/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockassemblies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockchains
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockchains/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockchains/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockpersisters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockpersisters/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockpersisters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockvalidators
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockvalidators/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - blockvalidators/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - bootstraps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - bootstraps/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - bootstraps/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - clusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - clusters/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - clusters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - coinbases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - coinbases/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - coinbases/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - faucets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - faucets/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - faucets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - legacies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - legacies/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - legacies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - peers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - peers/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - peers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - propagations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - propagations/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - propagations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - pruners
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - pruners/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - pruners/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - rpcs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - rpcs/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - rpcs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - subtreevalidators
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - subtreevalidators/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - subtreevalidators/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - utxopersisters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - utxopersisters/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - utxopersisters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - validators
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - validators/finalizers
    verbs:
      - update
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - validators/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: teranode-operator
  name: teranode-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: teranode-operator
  name: teranode-operator-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: teranode-operator
  name: teranode-operator-rpc-editor-role
rules:
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - rpcs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - rpcs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: teranode-operator
  name: teranode-operator-rpc-viewer-role
rules:
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - rpcs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - teranode.bsvblockchain.org
    resources:
      - rpcs/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: teranode-operator
  name: teranode-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teranode-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: teranode-operator-controller-manager
{{- if .Values.deployment.env.watch_namespace }}
{{- $namespaces := .Values.deployment.env.watch_namespace | split "," }}
{{- range $namespace := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teranode-operator-sr-role-binding
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teranode-operator-sr-role
subjects:
  - kind: ServiceAccount
    name: teranode-operator-service-runner
    namespace: {{ $namespace }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: teranode-operator
  name: teranode-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teranode-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: teranode-operator-controller-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: teranode-operator
  name: teranode-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teranode-operator-proxy-role
subjects:
  - kind: ServiceAccount
    name: teranode-operator-controller-manager
    namespace: {{ .Release.Namespace }}
