{{- if .Values.sampleCluster.enable }}
---
apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: sample-cluster
    app.kubernetes.io/name: sample-cluster
  name: sample-cluster
spec:
  alertSystem:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 1Gi
  asset:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: ast-grpc
        className: traefik-internal
        host: {{ .Values.sampleCluster.hostname }}
      httpIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        className: traefik-internal
        host: {{ .Values.sampleCluster.hostname }}
      httpsIngress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        className: traefik-internal
        host: {{ .Values.sampleCluster.hostname }}
  blockAssembly:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 4Gi
  blockPersister:
    enabled: false
    spec: {}
  blockValidator:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 2
            memory: 8Gi
  blockchain:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 1Gi
  bootstrap:
    enabled: false
    spec: {}
  coinbase:
    enabled: false
    spec: {}
  configMapName: shared-config
  image: {{ .Values.teranode.image.repository }}:{{ .Values.teranode.image.tag }}
  legacy:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 2
            memory: 8Gi
  peer:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: peer-grpc
        className: traefik-internal
        host: {{ .Values.sampleCluster.hostname }}
      wsIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-ws
        className: traefik-internal
        host: {{ .Values.sampleCluster.hostname }}
      wssIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-wss
        className: traefik-internal
        host: {{ .Values.sampleCluster.hostname }}
  propagation:
    enabled: false
    spec:
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: prop-grpc
        className: traefik-internal
        host: {{ .Values.sampleCluster.hostname }}
      serviceAnnotations:
        traefik.ingress.kubernetes.io/service.serversscheme: h2c
  rpc:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 1Gi
  subtreeValidator:
    enabled: true
    spec:
      deploymentOverrides:
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 8Gi
  sharedStorage:
    storageClass: fsx-lustre
    storageResources:
      requests:
        storage: 1200Gi
  utxoPersister:
    enabled: false
    spec: {}
  validator:
    enabled: false
    spec: {}
{{- end }}
