---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: teranode-operator
  name: teranode-operator-controller-manager
{{- if .Values.deployment.env.watch_namespace }}
{{- $namespaces := .Values.deployment.env.watch_namespace | split "," }}
{{- range $namespace := $namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teranode-operator-service-runner
  namespace: {{ $namespace | trim }}
{{- end }}
{{- end }}
